### PR TITLE
refactor: Unhandled promises and void promises

### LINKED ISSUE #2214: Extend eslint config to fix potential promise issues
There are some promises in the code that are not handled correctly. Add these rules to the eslint config and fix them:

Note: Running eslint with these rules might take a while

```
"@typescript-eslint/no-floating-promises":  "error",
"@typescript-eslint/await-thenable":  "error",
"@typescript-eslint/no-misused-promises":  "error",

"parser": "@typescript-eslint/parser",
"parserOptions": {
  "project": ["./tsconfig.json"]
},
```

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #2214

❗ Lets remove or hide the additional eslint config behind a command before merging this PR as it slows down lint checks significantly. ❗ 

## How this PR fixes it

- Removes `await act` calls in jest tests
- Uses `void <Function that returns a promise>` where it makes sense. There are still cases like inside onClick handlers where I left it as it was as it makes them less readable `onClick={(e) => void handleClick(e)}` vs. `onClick={handleClick}`

## How to test it

1. All e2e and unit tests should be green

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by katspaugh** [comment]
@usame-algan shall we close this? Was there any promise that was actually hanging that this lint rule caught?

**Comment by usame-algan** [comment]
> @usame-algan shall we close this? Was there any promise that was actually hanging that this lint rule caught?

Not hanging but we were using async in places where it wasn't necessary especially in tests (with act and waitFor) so the lint rule helped identify those places and clean them up.

**Comment by katspaugh** [comment]
@usame-algan gotcha. Shall we than rebase this branch on the protocol kit branch? There's probably going to be many merge conflicts.

**Comment by katspaugh** [comment]
@usame-algan it's out of sync again, shall we close it?

**Comment by usame-algan** [comment]
> @usame-algan it's out of sync again, shall we close it?

I will close this for now and will pick it up again when there is time. I think the redundant `await` calls and boilerplate in our tests are more important to refactor than adding `void` to some function calls so I could see fixing just that in a new PR and it should overall be smaller.

**Pull request closed without merging**
